seed : 2 
trial : 4 
Nx : 64 
Ny : 64
Nm : 64
pXmodes : 1 
pYmodes : 2 
pMmodes : 1 
ABFlag : 0
IsoDiffFlag : 1 
EqIcFlag : 0 
RandPerbAmpFlag : 0 
dt   : 0.001 
trec : 0.1 
tend  : 1.0 
bc : 2.0 
vD : 1.1          
Lx : 10.0 
Ly : 10.0 
Lrod : 1.1 
Dpar : 1.1 
Dperp : 1.1 
Dr : 1.1 
PertrbAmp : 0.00001
