seed : 2 
trial : 4 
Nx : 16
Ny : 16
Nm : 16
pXmodes : 4 
pYmodes : 4 
pMmodes : 4 
  # 0-Diff; 1-AB1; 2-AB2; 3-HAB1; 4-HAB2; 5-BHAB1; 6-BHAB2
StepFlag : 3
IsoDiffFlag : 0 
  # 0-Iso; 1-Equil
IcFlag : 1 
RandPerbAmpFlag : 0 
dt   : 0.001 
trec : 0.1
tend : 1.0
bc : 1.6 
vD : 1.0          
Lx : 10.0 
Ly : 10.0 
Lrod : 1.0 
Dpar : 1.0 
Dperp: 1.0 
Dr : 6.0 
PertrbAmp : 0.001
wrtOpFlag : 0
wrtRhoFlag : 0
