seed : 2 
trial : 4 
Nx : 64
Ny : 64
Nm : 64
pXmodes : 4 
pYmodes : 4 
pMmodes : 4 
ABFlag : 2
IsoDiffFlag : 1 
EqIcFlag : 0 
RandPerbAmpFlag : 0 
dt   : 0.001 
trec : 0.1
tend : 1.0
bc : 1.6 
vD : 1.0          
Lx : 10.0 
Ly : 10.0 
Lrod : 1.0 
Dpar : 1.0 
Dperp: 1.0 
Dr : 6.0 
PertrbAmp : 0.001
