seed : 2 
trial : 4 
Nx : 8 
Ny : 8 
Nm : 8 
pXmodes : 1 
pYmodes : 2 
pMmodes : 3 
IsoDiffFlag : 1 
EqIcFlag : 0 
RandPerbAmpFlag : 0 
dt   : 0.03 
trec : 0.2 
tend  : 5.0 
bc : 1.6 
vD : 1.1          
Lx : 10.1 
Ly : 10.1 
Lrod : 1.1 
Dpar : 1.1 
Dperp : 1.1 
Dr : 1.1 
PertrbAmp : 0.2 
