seed : 2 
trial : 4 
Nx : 8 
Ny : 8
Nm : 8
pXmodes : 2 
pYmodes : 2 
pMmodes : 2 
ABFlag : 1
IsoDiffFlag : 1 
EqIcFlag : 0 
RandPerbAmpFlag : 0 
dt   : 0.001 
trec : 0.1
tend  : 0.1 
bc : 1.0 
vD : 1.0          
Lx : 10.0 
Ly : 10.0 
Lrod : 1.0 
Dpar : 1.0 
Dperp : 1.0 
Dr : 1.0 
PertrbAmp : 0.001
